# Generated by Django 5.1.1 on 2024-09-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category (must be unique).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time the category was updated.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time when the category was created.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
