# Generated by Django 5.1.1 on 2024-09-23 10:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        ('reports', '0002_problemcategory_problemreported_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreported',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='categories.category'),
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-day', '-start_hour'], 'verbose_name': 'Production Report', 'verbose_name_plural': 'Production Reports'},
        ),
        migrations.RemoveField(
            model_name='problemreported',
            name='problem_id',
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='breakdown',
            field=models.PositiveIntegerField(help_text='Duration of breakdown in minutes.'),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='public',
            field=models.BooleanField(default=False, help_text='Whether the problem is visible to all users.'),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_hour',
            field=models.IntegerField(choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], help_text='End hour of the production period (0-23).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='execution',
            field=models.PositiveIntegerField(help_text='Actual production achieved.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='plan',
            field=models.PositiveIntegerField(help_text='Planned production for the period.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_hour',
            field=models.IntegerField(choices=[(0, '00'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], help_text='Start hour of the production period (0-23).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('execution__lte', models.F('plan'))), name='execution_lte_plan'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('end_hour__gt', models.F('start_hour'))), name='end_hour_gt_start_hour'),
        ),
        migrations.DeleteModel(
            name='ProblemCategory',
        ),
    ]
