# Generated by Django 5.1.1 on 2024-09-23 12:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_problemreported_category_alter_report_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Problem Category',
                'verbose_name_plural': 'Problem Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created'], 'verbose_name': 'Production Report', 'verbose_name_plural': 'Production Reports'},
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='execution_lte_plan',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='end_hour_gt_start_hour',
        ),
        migrations.AddField(
            model_name='problemreported',
            name='problem_id',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the problem.', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='breakdown',
            field=models.PositiveIntegerField(help_text='Breakdown or severity level of the problem.'),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='public',
            field=models.BooleanField(default=False, help_text='Whether the problem is visible to the public.'),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_hour',
            field=models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], help_text='End hour of the production period (1-24).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='execution',
            field=models.PositiveBigIntegerField(help_text='Actual production achieved.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='plan',
            field=models.PositiveBigIntegerField(help_text='Planned production for the day.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_hour',
            field=models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], help_text='Start hour of the production period (1-24).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='problemreported',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='reports.problemcategory'),
        ),
    ]
